version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: ['celery', '-A', 'app.tasks', 'worker', '-l', 'INFO']
    environment:
     - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - rabbitmq
      - redis
      - rproxy

  rproxy:
    hostname: rproxy
    image: mattes/rotating-proxy:latest
    container_name: rproxy
    environment:
      - tors=25
    ports:
      - "5566:5566"
      - "4444:4444"

  worker:
    build:
      context: .
      dockerfile: run
    container_name: worker
    volumes:
      - ./:/app/
    depends_on:
      - celery
