version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['celery', 'worker', '-A', 'app.tasks', '-l', 'INFO']
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - rabbitmq
      - redis

  rproxy:
    hostname: rproxy
    image: mattes/rotating-proxy:latest
    environment:
      - tors=25
    ports:
      - "5566:5566"
      - "4444:4444"

